# Generated by Django 5.2.1 on 2025-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EXPEDIENTE", models.CharField(db_column="N.º EXPED", max_length=100)),
                ("PROCEDIMIENTO", models.CharField(max_length=255)),
                ("TIPOLOGÍA", models.CharField(max_length=255)),
                (
                    "FECHA_FIRMA",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "DURACIÓN_CONTRATO",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("FECHA_FIN", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "PRORROGA",
                    models.CharField(
                        blank=True, db_column="¿PRÓRROGAS?", max_length=255, null=True
                    ),
                ),
                (
                    "FECHA_FIN_PRORROGA",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "CANTIDAD_ECONOMICA_MAX",
                    models.DecimalField(
                        blank=True,
                        db_column="CANTIDAD ECONÓMICA MÁX (IVA INCLUIDO)",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("ESTADO", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ESTADO_CONTINUACION",
                    models.TextField(
                        blank=True, db_column="ESTADO CONTINUACION", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("ip", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=200)),
                ("codigo_fundanet", models.CharField(max_length=100, unique=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "overhead",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("ruta", models.CharField(blank=True, max_length=200, null=True)),
                ("factura", models.CharField(blank=True, max_length=20, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "estado_contabilidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contactos_fra",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
