# Generated by Django 5.2.1 on 2025-05-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_concurso_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concurso",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
