# Generated by Django 5.2.1 on 2025-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0003_alter_concurso_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concurso",
            name="EXPEDIENTE",
            field=models.CharField(db_column="N.º EXPED", max_length=100, unique=True),
        ),
    ]
