# Generated by Django 5.2.1 on 2025-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0005_usuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
        migrations.AddField(
            model_name="convocatoria",
            name="nif_tercero",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="convocatoria",
            name="objeto",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="convocatoria",
            name="pais_ccaa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="País/CCAA"
            ),
        ),
    ]
