# Generated by Django 5.2.1 on 2025-06-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ensayos_clinicos", "0009_rename_importe_facturadetalle_cantidad_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioContratacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceso_codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=150)),
                ("direccion_completa", models.CharField(max_length=255)),
                ("poblacion", models.CharField(max_length=100)),
                ("provincia", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=10)),
                ("nacionalidad", models.CharField(max_length=100)),
                ("nif", models.CharField(blank=True, max_length=20, null=True)),
                ("nie", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "carta_identidad",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pasaporte", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField()),
                ("sexo", models.CharField(max_length=20)),
                (
                    "fotocopia_tarjeta_inem",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "soporte_documental_meritos",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "certificado_titularidad_bancaria",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "certificado_delitos_sexuales",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "curriculum",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "vida_laboral",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "fotocopia_master_doctorado",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                ("nivel_estudios", models.CharField(max_length=100)),
                ("especialidad", models.CharField(max_length=100)),
                ("inscrito_sepe", models.BooleanField(default=False)),
                ("mayor_30_sepe", models.BooleanField(default=False)),
                ("discapacitado", models.BooleanField(default=False)),
                ("excluido_social", models.BooleanField(default=False)),
                ("victima_violencia_domestica", models.BooleanField(default=False)),
                ("mujer_reincorporada", models.BooleanField(default=False)),
                ("capacidad_intelectual_limite", models.BooleanField(default=False)),
                ("contrato_temporal_6m_fibh", models.BooleanField(default=False)),
                ("contrato_indefinido_12m_fibh", models.BooleanField(default=False)),
                (
                    "contrato_indefinido_3m_otra_empresa",
                    models.BooleanField(default=False),
                ),
                ("tipo_contrato", models.CharField(max_length=100)),
                ("contrato_duracion", models.IntegerField(blank=True, null=True)),
                ("causa_contrato", models.TextField(blank=True, null=True)),
                (
                    "titulacion_practicas",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("fecha_obtencion_titulacion", models.DateField(blank=True, null=True)),
                (
                    "jornada",
                    models.CharField(
                        choices=[("Completa", "Completa"), ("Parcial", "Parcial")],
                        max_length=100,
                    ),
                ),
                ("horas_semana", models.IntegerField(blank=True, null=True)),
                ("distribucion_jornada", models.TextField(blank=True, null=True)),
                ("convocatoria", models.CharField(max_length=100)),
                ("categoria_area", models.CharField(max_length=10)),
                ("categoria_grupo", models.CharField(max_length=10)),
                ("categoria_profesional", models.CharField(max_length=100)),
                ("prestara_servicios_como", models.CharField(max_length=150)),
                (
                    "tipo_personal",
                    models.CharField(
                        choices=[
                            ("PI", "Personal Investigador (Área 1)"),
                            ("SOPORTE", "Soporte Científico-Técnico (Área 2)"),
                            ("GESTION", "Administración y Gestión (Área 3)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("funciones", models.TextField()),
                ("logos", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("clausulas_adicionales", models.TextField(blank=True, null=True)),
                ("objeto_contrato", models.TextField()),
                ("financiacion", models.TextField()),
                ("aplica_tablas_convenio", models.BooleanField(default=True)),
                (
                    "salario_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "carrera_profesional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "complementos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salario_fijo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "coste_fijado_convocatoria",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "importe_coste_empresa_anual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "requiere_autorizacion_hacienda",
                    models.BooleanField(blank=True, null=True),
                ),
                ("rellenado_por_empleado", models.BooleanField(default=False)),
                ("rellenado_por_empresa", models.BooleanField(default=False)),
                ("enviado_a_fundanet", models.BooleanField(default=False)),
                ("enviado_a_gestoria", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios",
                        to="ensayos_clinicos.usuario",
                    ),
                ),
            ],
        ),
    ]
