# Generated by Django 5.2.1 on 2025-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="apellidos",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="direccion_completa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="nacionalidad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="poblacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="provincia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="sexo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
