# Generated by Django 5.2.1 on 2025-06-11 12:39

import rrhh.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0002_alter_formulariocontratacion_apellidos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="certificado_delitos_sexuales",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="certificado_titularidad_bancaria",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="curriculum",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="fotocopia_master_doctorado",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="fotocopia_tarjeta_inem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="soporte_documental_meritos",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="vida_laboral",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
    ]
