# Generated by Django 5.2.1 on 2025-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rrhh",
            "0003_alter_formulariocontratacion_certificado_delitos_sexuales_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_postulacion", models.DateTimeField(auto_now_add=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
            ],
        ),
    ]
