# Generated by Django 5.2.1 on 2025-06-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0004_candidato"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="seleccionado",
            field=models.BooleanField(default=False),
        ),
    ]
