# Generated by Django 5.2.1 on 2025-06-26 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0005_candidato_seleccionado"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="fecha_seleccionado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidato",
            name="token_acceso",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
