# Generated by Django 5.2.1 on 2025-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0006_candidato_fecha_seleccionado_candidato_token_acceso"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="ficha_firmada",
            field=models.FileField(blank=True, null=True, upload_to="fichas_firmadas/"),
        ),
    ]
