# Generated by Django 5.2.1 on 2025-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0007_candidato_ficha_firmada"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="certificado_penales",
            field=models.FileField(blank=True, null=True, upload_to="documentos/"),
        ),
        migrations.AddField(
            model_name="candidato",
            name="titulacion",
            field=models.FileField(blank=True, null=True, upload_to="documentos/"),
        ),
        migrations.AddField(
            model_name="candidato",
            name="vida_laboral",
            field=models.FileField(blank=True, null=True, upload_to="documentos/"),
        ),
    ]
