# Generated by Django 5.2.1 on 2025-07-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0008_candidato_certificado_penales_candidato_titulacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariocontratacion",
            name="empleado",
        ),
    ]
