# Generated by Django 5.2.1 on 2025-07-01 11:36

import rrhh.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0009_remove_formulariocontratacion_empleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="ficha_firmada",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fichas_firmadas/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
    ]
