# Generated by Django 5.2.1 on 2025-07-08 12:39

import rrhh.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0010_formulariocontratacion_ficha_firmada"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_capacidad_intelectual_limite",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_contrato_indefinido_12m_fibh",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_contrato_indefinido_3m_otra_empresa",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_contrato_temporal_6m_fibh",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_discapacitado",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_excluido_social",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_inscrito_sepe",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_mayor_30_sepe",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_mujer_reincorporada",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="documento_victima_violencia_domestica",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/",
                validators=[rrhh.validators.validar_tamano_archivo],
            ),
        ),
    ]
