# Generated by Django 5.2.1 on 2025-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rrhh",
            "0011_formulariocontratacion_documento_capacidad_intelectual_limite_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="capacidad_intelectual_limite",
            field=models.BooleanField(
                default=False, verbose_name="Persona con capacidad intelectual límite"
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="contrato_indefinido_12m_fibh",
            field=models.BooleanField(
                default=False,
                verbose_name="Contrato indefinido de al menos 12 meses en la FIBHULP",
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="contrato_indefinido_3m_otra_empresa",
            field=models.BooleanField(
                default=False,
                verbose_name="Contrato indefinido de al menos 3 meses en otra empresa",
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="contrato_temporal_6m_fibh",
            field=models.BooleanField(
                default=False,
                verbose_name="Contrato temporal de al menos 6 meses en la FIBHULP",
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="discapacitado",
            field=models.BooleanField(
                default=False, verbose_name="Discapacidad reconocida ≥ 33%"
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="excluido_social",
            field=models.BooleanField(
                default=False, verbose_name="Situación de exclusión social acreditada"
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="inscrito_sepe",
            field=models.BooleanField(
                default=False,
                verbose_name="Inscrito/a como demandante de empleo en el SEPE",
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="mayor_30_sepe",
            field=models.BooleanField(
                default=False,
                verbose_name="Menor de 30 años inscrito/a como demandante de empleo",
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="mujer_reincorporada",
            field=models.BooleanField(
                default=False,
                verbose_name="Mujer reincorporada en los 2 años siguientes al parto",
            ),
        ),
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="victima_violencia_domestica",
            field=models.BooleanField(
                default=False, verbose_name="Víctima de violencia de género o doméstica"
            ),
        ),
    ]
