# Generated by Django 5.2.1 on 2025-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rrhh",
            "0012_alter_formulariocontratacion_capacidad_intelectual_limite_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="tipo_contrato",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Indefinido",
                        [
                            ("indefinido_ordinario", "Ordinario"),
                            (
                                "indefinido_ct",
                                "Actividades Científico-Técnicas (Apartado 3.B)",
                            ),
                            (
                                "transformacion_ct",
                                "Transformación Actividades Científico-Técnicas (Apartado 3.B)",
                            ),
                        ],
                    ),
                    (
                        "Temporal",
                        [
                            (
                                "temporal_fondos_europeos",
                                "Vinculado a fondos europeos (NO competitivos)",
                            ),
                            (
                                "temporal_prtr",
                                "Plan de Recuperación, Transformación y Resiliencia (PRTR)",
                            ),
                            (
                                "temporal_produccion_imprevisible",
                                "Producción imprevisible (máx. 6 meses) → Causa",
                            ),
                            (
                                "temporal_produccion_previsible",
                                "Producción previsible (empresa máx. 90 días/año) → Causa",
                            ),
                            ("temporal_interinidad", "Interinidad → Causa"),
                            (
                                "temporal_practicas",
                                "Prácticas → Titulación y fecha obtención",
                            ),
                            ("predoc", "PREDOC en formación"),
                            ("postdoc", "De acceso a SECTI (postdoc)"),
                            ("distinguido", "Investigador distinguido"),
                        ],
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
