# Generated by Django 5.2.1 on 2025-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0013_alter_formulariocontratacion_tipo_contrato"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariocontratacion",
            name="fecha_obtencion_titulacion",
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="titulacion_y_fecha",
            field=models.DateField(blank=True, null=True),
        ),
    ]
