# Generated by Django 5.2.1 on 2025-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rrhh",
            "0014_remove_formulariocontratacion_fecha_obtencion_titulacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="titulacion_y_fecha",
            field=models.CharField(blank=True, null=True),
        ),
    ]
