# Generated by Django 5.2.1 on 2025-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0015_alter_formulariocontratacion_titulacion_y_fecha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariocontratacion",
            name="contrato_duracion",
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="duracion",
            field=models.IntegerField(
                blank=True, help_text="Duración del contrato en meses", null=True
            ),
        ),
    ]
