# Generated by Django 5.2.1 on 2025-07-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0016_remove_formulariocontratacion_contrato_duracion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="observaciones_jornada",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
