# Generated by Django 5.2.1 on 2025-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0017_formulariocontratacion_observaciones_jornada"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="direccion_centro",
            field=models.CharField(
                choices=[
                    ("CL Diego de León 62", "H. Princesa"),
                    ("CL del Maestro Vives, 2", "H. Santa Cristina"),
                    ("Av. de Menéndez Pelayo, 65", "H. N. Jesús"),
                ],
                default="CL Diego de León 62",
                max_length=100,
            ),
        ),
    ]
