# Generated by Django 5.2.1 on 2025-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0018_formulariocontratacion_direccion_centro"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="proceso_codigo",
            field=models.CharField(
                default="sin asignar",
                help_text="Código de la oferta a la que se inscribe el candidato",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
