# Generated by Django 5.2.1 on 2025-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0019_candidato_proceso_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulariocontratacion",
            name="clausulas_adicionales",
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="clausulas_adicionales_rrhh",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Cláusulas adicionales extraordinarias",
            ),
        ),
    ]
