# Generated by Django 5.2.1 on 2025-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0020_remove_formulariocontratacion_clausulas_adicionales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="puesto",
            field=models.CharField(default="habichuelas", max_length=100),
            preserve_default=False,
        ),
    ]
