# Generated by Django 5.2.1 on 2025-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0021_formulariocontratacion_puesto"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="ip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
