# Generated by Django 5.2.1 on 2025-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0022_formulariocontratacion_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="alta",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de alta"),
        ),
    ]
