# Generated by Django 5.2.1 on 2025-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0023_formulariocontratacion_alta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocontratacion",
            name="funciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
