# Generated by Django 5.2.1 on 2025-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0024_alter_formulariocontratacion_funciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
    ]
