# Generated by Django 5.2.1 on 2025-07-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0025_formulariocontratacion_cv"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Candidato",
        ),
    ]
