# Generated by Django 5.2.1 on 2025-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0026_delete_candidato"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariocontratacion",
            name="seleccionado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="formulariocontratacion",
            name="token_acceso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
