# Generated by Django 5.2.1 on 2025-05-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosEnsayo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("Enero", "Enero"),
                            ("Febrero", "Febrero"),
                            ("Marzo", "Marzo"),
                            ("Abril", "Abril"),
                            ("Mayo", "Mayo"),
                            ("Junio", "Junio"),
                            ("Julio", "Julio"),
                            ("Agosto", "Agosto"),
                            ("Septiembre", "Septiembre"),
                            ("Octubre", "Octubre"),
                            ("Noviembre", "Noviembre"),
                            ("Diciembre", "Diciembre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ensayos", models.PositiveIntegerField(default=0)),
                ("observacionales", models.PositiveIntegerField(default=0)),
                ("adendas", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
