# Generated by Django 5.2.1 on 2025-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.PositiveIntegerField()),
                ("mes", models.CharField(max_length=3)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="datosensayo",
            name="año",
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
