# Generated by Django 5.2.1 on 2025-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0002_facturamensual_datosensayo_año"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturamensual",
            name="numero_facturas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
