# Generated by Django 5.2.1 on 2025-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0003_facturamensual_numero_facturas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturamensual",
            name="cantidad",
            field=models.FloatField(),
        ),
    ]
