# Generated by Django 5.2.1 on 2025-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0004_alter_facturamensual_cantidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("es_backup", models.BooleanField(default=False)),
            ],
        ),
    ]
