# Generated by Django 5.2.1 on 2025-05-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0005_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="secciones",
            field=models.CharField(default="1", max_length=100),
        ),
    ]
