# Generated by Django 5.2.1 on 2025-06-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0006_usuario_secciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturamensual",
            name="fecha_ultimo_cobro",
            field=models.DateField(blank=True, null=True),
        ),
    ]
