# Generated by Django 5.2.1 on 2025-06-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0007_facturamensual_fecha_ultimo_cobro"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=15)),
                ("fecha_emision", models.DateField(blank=True, null=True)),
                ("fecha_ultimo_cobro", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
