# Generated by Django 5.2.1 on 2025-06-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ensayos_clinicos", "0008_facturadetalle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facturadetalle",
            old_name="importe",
            new_name="cantidad",
        ),
        migrations.RemoveField(
            model_name="facturadetalle",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="facturadetalle",
            name="año",
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facturadetalle",
            name="concepto",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facturadetalle",
            name="identificador",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="facturadetalle",
            name="mes",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
